default_config:

# miele:
#   sensors:
#     - id: sensor.tumble_dryer_program
#       program_ids:
#         - value_raw: 14
#           value: shirts

logger:
  default: info
  logs:
    custom_components.miele: debug
    pymiele: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
debugpy: